"""EEL2 Code Generator.

Walks the AST and emits Python source code as a string.
"""

from .parser import (
    ASTNode,
    Assign,
    BinOp,
    Call,
    Ident,
    If,
    Index,
    Loop,
    Number,
    Program,
    Section,
    StringLit,
    Ternary,
    UnaryOp,
    While,
)

CONSTANT_MAP: dict[str, str] = {
    "$pi": "math.pi",
    "$phi": "((1.0 + math.sqrt(5.0)) / 2.0)",
    "$e": "math.e",
}

BUILTIN_MAP: dict[str, str] = {
    "sin": "math.sin",
    "cos": "math.cos",
    "tan": "math.tan",
    "sqrt": "math.sqrt",
    "abs": "abs",
    "log": "math.log",
    "log10": "math.log10",
    "exp": "math.exp",
    "floor": "math.floor",
    "ceil": "math.ceil",
    "min": "min",
    "max": "max",
    "sign": "_eel2_sign",
    "pow": "math.pow",
    "memset": "_eel2_memset",
    "memcpy": "_eel2_memcpy",
}


class CodeGen:
    """Generates Python source code from an EEL2 AST."""

    def __init__(self) -> None:
        self.indent = 0
        self.lines: list[str] = []

    def emit(self, line: str = "") -> None:
        """Append an indented line to the output buffer.

        Args:
            line: Source line to emit (without leading indentation).
        """
        self.lines.append("    " * self.indent + line)

    def generate(self, program: Program) -> str:
        """Generate a complete Python source string from a Program AST.

        Args:
            program: The root Program node to generate code for.

        Returns:
            A Python source string ready for exec() or writing to a file.
        """
        self.emit('"""Auto-generated by eel2py. Do not edit."""')
        self.emit("import math")
        self.emit(
            "from eel2py.runtime import _eel2_sign, _eel2_memset, _eel2_memcpy, _eel2_assign"
        )
        self.emit()

        for section in program.sections:
            if section.name == "init":
                self._gen_init(section)
            elif section.name == "slider":
                self._gen_slider(section)
            elif section.name == "sample":
                self._gen_sample(section)

        return "\n".join(self.lines)

    def _gen_init(self, section: Section) -> None:
        """Emit the init() function from an @init section.

        Args:
            section: The @init Section node.
        """
        self.emit("def init(state: dict) -> None:")
        self.indent += 1
        self.emit('"""Runs once at plugin load. Initializes state."""')
        if not section.body:
            self.emit("pass")
        else:
            for stmt in section.body:
                self._gen_stmt(stmt)
        self.indent -= 1
        self.emit()

    def _gen_slider(self, section: Section) -> None:
        """Emit the on_slider() function from a @slider section.

        Args:
            section: The @slider Section node.
        """
        self.emit("def on_slider(state: dict) -> None:")
        self.indent += 1
        self.emit('"""Runs when a slider changes."""')
        if not section.body:
            self.emit("pass")
        else:
            for stmt in section.body:
                self._gen_stmt(stmt)
        self.indent -= 1
        self.emit()

    def _gen_sample(self, section: Section) -> None:
        """Emit process_sample() and process_block() from a @sample section.

        Args:
            section: The @sample Section node.
        """
        self.emit(
            "def process_sample(left: float, right: float, state: dict) -> tuple:"
        )
        self.indent += 1
        self.emit('"""Process one stereo sample. Returns (left, right)."""')
        self.emit('state["spl0"] = left')
        self.emit('state["spl1"] = right')
        for stmt in section.body:
            self._gen_stmt(stmt)
        self.emit('return state.get("spl0", 0.0), state.get("spl1", 0.0)')
        self.indent -= 1
        self.emit()

        self.emit("def process_block(samples, state: dict):")
        self.indent += 1
        self.emit(
            '"""Process a numpy array of shape (N, 2). Returns processed array."""'
        )
        self.emit("import numpy as np")
        self.emit("out = np.zeros_like(samples)")
        self.emit("for i in range(len(samples)):")
        self.indent += 1
        self.emit(
            "l, r = process_sample(float(samples[i, 0]), float(samples[i, 1]), state)"
        )
        self.emit("out[i, 0] = l")
        self.emit("out[i, 1] = r")
        self.indent -= 1
        self.emit("return out")
        self.indent -= 1
        self.emit()

    def _gen_stmt(self, node: ASTNode) -> None:
        """Emit a statement from an AST node.

        Args:
            node: An AST statement node (Assign, If, While, Loop, or expression).
        """
        if isinstance(node, Assign):
            target = self._gen_assign_target(node.target)
            value = self._gen_expr(node.value)
            if node.op == "=":
                self.emit(f"{target} = float({value})")
            else:
                self.emit(f"{target} {node.op} float({value})")
        elif isinstance(node, If):
            cond = self._gen_expr(node.cond)
            self.emit(f"if {cond}:")
            self.indent += 1
            if node.then:
                for s in node.then:
                    self._gen_stmt(s)
            else:
                self.emit("pass")
            self.indent -= 1
            if node.else_:
                self.emit("else:")
                self.indent += 1
                for s in node.else_:
                    self._gen_stmt(s)
                self.indent -= 1
        elif isinstance(node, While):
            cond = self._gen_expr(node.cond)
            self.emit(f"while {cond}:")
            self.indent += 1
            for s in node.body:
                self._gen_stmt(s)
            self.indent -= 1
        elif isinstance(node, Loop):
            count = self._gen_expr(node.count)
            self.emit(f"for _loop_i in range(int({count})):")
            self.indent += 1
            self._gen_stmt(node.body)
            self.indent -= 1
        else:
            self.emit(self._gen_expr(node))

    def _gen_assign_target(self, node: Ident | Index) -> str:
        """Emit the left-hand side of an assignment.

        Args:
            node: An Ident or Index node representing the assignment target.

        Returns:
            Python expression string for the assignment target.
        """
        if isinstance(node, Ident):
            return f'state["{node.name}"]'
        arr = self._gen_expr(node.array)
        idx = self._gen_expr(node.idx)
        return f"{arr}[int({idx})]"

    def _gen_expr(self, node: ASTNode) -> str:
        """Emit a Python expression string from an AST expression node.

        Args:
            node: Any expression AST node.

        Returns:
            Python expression string.
        """
        if isinstance(node, Number):
            return repr(node.value)
        if isinstance(node, StringLit):
            return repr(node.value)
        if isinstance(node, Ident):
            if node.name in CONSTANT_MAP:
                return CONSTANT_MAP[node.name]
            return f'state.get("{node.name}", 0.0)'
        if isinstance(node, BinOp):
            left = self._gen_expr(node.left)
            right = self._gen_expr(node.right)
            if node.op == "^":
                return f"({left} ** {right})"
            if node.op == "&&":
                return f"(({left}) and ({right}))"
            if node.op == "||":
                return f"(({left}) or ({right}))"
            return f"({left} {node.op} {right})"
        if isinstance(node, UnaryOp):
            operand = self._gen_expr(node.operand)
            if node.op == "!":
                return f"(not ({operand}))"
            return f"({node.op}{operand})"
        if isinstance(node, Ternary):
            cond = self._gen_expr(node.cond)
            then = self._gen_expr(node.then)
            else_ = self._gen_expr(node.else_)
            return f"(({then}) if ({cond}) else ({else_}))"
        if isinstance(node, Call):
            py_fn = BUILTIN_MAP.get(node.name, node.name)
            args = ", ".join(self._gen_expr(a) for a in node.args)
            return f"{py_fn}({args})"
        if isinstance(node, Index):
            arr = self._gen_expr(node.array)
            idx = self._gen_expr(node.idx)
            return f"{arr}[int({idx})]"
        if isinstance(node, Assign):
            name = node.target.name if isinstance(node.target, Ident) else "?"
            value = self._gen_expr(node.value)
            return f'_eel2_assign(state, "{name}", {value})'
        return f"# UNHANDLED: {node}"
